import { runFullRegression } from "../lib/dry-run/regression-runner";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("🚀 Starting AI Regression CLI...");
  
  const profile = (process.argv[2] as any) || "balanced";
  const user = process.env.USER || process.env.USERNAME || "system";
  const env = process.env.NODE_ENV || "local";
  const notes = process.argv[3] || "CLI run";

  console.log(`📡 Profile: ${profile.toUpperCase()} | User: ${user} | Env: ${env}`);

  const summary = await runFullRegression(profile, undefined, { user, env, notes });

  console.log("\n--- REGRESSION SUMMARY ---");
  console.log(`Total: ${summary.total}`);
  console.log(`Passed: ${summary.passed}`);
  console.log(`Failed: ${summary.passed < summary.total ? "❌" : "✅"} ${summary.failed}`);
  console.log(`Gate Status: [${summary.gateStatus}]`);

  // Generate Markdown Summary
  const mdPath = path.join(process.cwd(), "regression-summary.md");
  const mdContent = `
# 🚦 AI QA Regression Report
Generated: \`${summary.metadata.generatedAt}\`
By: **${summary.metadata.generatedBy}** (@${summary.metadata.environment})
Gate Profile: \`${summary.profile.toUpperCase()}\`
Catalog Hash: \`${summary.metadata.catalogFingerprint}\`

## 📊 Executive Summary
| Metric | Value |
| :--- | :--- |
| **Gate Status** | ${summary.gateStatus === "PASS" ? "🟢 PASS" : summary.gateStatus === "WARN" ? "🟡 WARN" : "🔴 FAIL"} |
| **Overall Accuracy** | **${((summary.passed / summary.total) * 100).toFixed(1)}%** (${summary.passed}/${summary.total}) |
| Intent Success | ${((1 - summary.intentMismatches / summary.total) * 100).toFixed(1)}% |
| Handoff Success | ${((1 - summary.handoffMismatches / summary.total) * 100).toFixed(1)}% |

${summary.gateReasons.length > 0 ? `### ⚠️ Blocking Issues\n${summary.gateReasons.map(r => `> - ${r}`).join("\n")}` : ""}

## 🏷️ Performance by Tag
${Object.entries(summary.tagStats).map(([tag, stats]) => {
  const rate = Math.round(stats.passed / stats.total * 100);
  return `- **${tag}**: \`${rate}%\` (${stats.passed}/${stats.total})`;
}).join("\n")}

## 📝 Provenance & Notes
- **Notes**: ${summary.metadata.notes}
- **Schema**: v${summary.metadata.schemaVersion}
- **Catalog Version**: ${summary.metadata.catalogVersion}

---
*Generated by AI Governance Layer v1.2*
  `;
  fs.writeFileSync(mdPath, mdContent);
  console.log(`\n📝 Markdown summary saved to: ${mdPath}`);

  // Export report to a temp file
  const reportPath = path.join(process.cwd(), "regression-report-cli.json");
  fs.writeFileSync(reportPath, JSON.stringify(summary, null, 2));
  console.log(`📄 JSON report saved to: ${reportPath}`);

  if (summary.gateStatus === "FAIL") {
    console.log("\n🔴 GATE REJECTED. Production deployment blocked.");
    process.exit(1);
  } else {
    console.log("\n🟢 GATE PASSED. Ready for deployment.");
    process.exit(0);
  }
}

main().catch(err => {
  console.error("Fatal Error:", err);
  process.exit(1);
});
